# NumPy

In [3]:
#NumPy Arrays
mylist=[1,2,3]


In [4]:
import numpy as np

In [5]:
arr=np.array(mylist)

In [6]:
arr

array([1, 2, 3])

In [8]:
mat=[[1,2,3],[4,5,6],[7,8,9]]
marr=np.array(mat)
marr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
#inbuilt arrays
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#even
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.rand(2)

array([0.36664445, 0.32601917])

In [26]:
np.random.rand(2,2)

array([[0.47970378, 0.09997491],
       [0.04490308, 0.36947657]])

In [28]:
#normal dist
np.random.randn(2,2)

array([[-0.01219522, -1.95788866],
       [-1.84218888, -1.08464903]])

In [32]:
np.random.randint(1,200,10)

array([ 91,  56,  30, 151,  18, 138,   4,  51,  92, 163])

In [34]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
rnarr=np.random.randint(1,50,10)

In [39]:
rnarr.max()

43

In [40]:
arr.max()

24

In [41]:
arr.min()

0

In [42]:
arr.argmax()

24

In [43]:
arr.argmin()

0

In [49]:
arr.shape
arr=arr.reshape(5,5)

In [50]:
arr.shape

(5, 5)

In [51]:
arr.dtype

dtype('int64')

## Numpy array Indexing

In [3]:
import numpy as np

In [5]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

8

In [8]:
arr[0:4]

array([0, 1, 2, 3])

In [9]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[-1:]

array([10])

In [12]:
arr[-1]

10

In [13]:
arr[1]=100

In [14]:
arr

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [15]:
slicearr = arr[0:5]

In [16]:
slicearr

array([  0, 100,   2,   3,   4])

In [21]:
slicearr[:]=97

In [22]:
slicearr

array([97, 97, 97, 97, 97])

In [23]:
arr

array([97, 97, 97, 97, 97,  5,  6,  7,  8,  9, 10])

In [24]:
copyarr=arr.copy()

In [25]:
copyarr[1:5]=123

In [26]:
copyarr

array([ 97, 123, 123, 123, 123,   5,   6,   7,   8,   9,  10])

In [27]:
arr

array([97, 97, 97, 97, 97,  5,  6,  7,  8,  9, 10])

In [28]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr_2d[0][0]

1

In [31]:
arr_2d[2,1]

8

In [33]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [36]:
bool_arr=arr_2d >3

In [37]:
arr_2d[bool_arr]

array([4, 5, 6, 7, 8, 9])

In [38]:
arr_2d[arr_2d>2]

array([3, 4, 5, 6, 7, 8, 9])

#  NumPy Operations

## * Array with Array

## * Array with Scalars

## * Universal Array Functions


In [1]:
import numpy as np

In [10]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr=arr +arr

In [12]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
arr=arr *10
arr

array([   0,  200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])

In [21]:
arr-1
arr

array([   0,  200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])

In [24]:
arr=1/arr
arr

array([   0.,  200.,  400.,  600.,  800., 1000., 1200., 1400., 1600.,
       1800., 2000.])

In [25]:
arr**2

array([      0.,   40000.,  160000.,  360000.,  640000., 1000000.,
       1440000., 1960000., 2560000., 3240000., 4000000.])

In [26]:
np.sqrt(arr)

array([ 0.        , 14.14213562, 20.        , 24.49489743, 28.28427125,
       31.6227766 , 34.64101615, 37.41657387, 40.        , 42.42640687,
       44.72135955])

In [27]:
np.log(arr)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 5.29831737, 5.99146455, 6.39692966, 6.68461173,
       6.90775528, 7.09007684, 7.24422752, 7.37775891, 7.49554194,
       7.60090246])

In [28]:
np.sin(arr)

array([ 0.        , -0.8732973 , -0.85091936,  0.04418245,  0.89396965,
        0.82687954, -0.08827861, -0.91289604, -0.80122479,  0.13220235,
        0.9300395 ])

# Pandas

## * Series


In [1]:
import numpy as np
import pandas as pd

In [4]:
mydata=[1,2,3]
mylabels=['a','b','c']
np.array(mydata)

0    1
1    2
2    3
dtype: int64

In [5]:
pd.Series(data=mydata)

0    1
1    2
2    3
dtype: int64

In [10]:
pd.Series(data=mydata,index=mylabels)

a    1
b    2
c    3
dtype: int64

In [7]:
d={'a':1,'b':2,'c':3}

In [9]:
d

{'a': 1, 'b': 2, 'c': 3}

In [11]:
pd.Series(d)

a    1
b    2
c    3
dtype: int64

In [13]:
ser1 = pd.Series([1,2,3],['GER','USA','IND'])
ser1

GER    1
USA    2
IND    3
dtype: int64

In [19]:
ser2 = pd.Series([4,5,6,7],['NZ','GB','SL','IND'])
ser2

NZ     4
GB     5
SL     6
IND    7
dtype: int64

In [17]:
ser1['GER']

1

In [20]:
ser1 + ser2

GB      NaN
GER     NaN
IND    10.0
NZ      NaN
SL      NaN
USA     NaN
dtype: float64

# Pandas -DataFrames


In [1]:
import numpy as np
import pandas as pd

In [4]:
from numpy.random import randn
#randn is randn generates an array of shape (d0, d1, …, dn), filled with random floats 
#sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1

In [5]:
np.random.seed(101)

In [12]:
df=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [23]:
df

W         X         Y         Z
A -0.497104 -0.754070 -0.943406  0.484752
B -0.116773  1.901755  0.238127  1.996652
C -0.993263  0.196800 -1.136645  0.000366
D  1.025984 -0.156598 -0.031579  0.649826
E  2.154846 -0.610259 -0.755325 -0.346419

In [24]:
df['W']
#like a series

A   -0.497104
B   -0.116773
C   -0.993263
D    1.025984
E    2.154846
Name: W, dtype: float64

In [25]:
type(df['W'])

pandas.core.series.Series

In [28]:
df[['X','Y']]

X         Y
A -0.754070 -0.943406
B  1.901755  0.238127
C  0.196800 -1.136645
D -0.156598 -0.031579
E -0.610259 -0.755325

In [31]:
df['new']=df['X']+df['Y']

In [32]:
df['new']

A   -1.697476
B    2.139882
C   -0.939845
D   -0.188177
E   -1.365584
Name: new, dtype: float64

In [34]:
df.drop('new',axis=1)

W         X         Y         Z
A -0.497104 -0.754070 -0.943406  0.484752
B -0.116773  1.901755  0.238127  1.996652
C -0.993263  0.196800 -1.136645  0.000366
D  1.025984 -0.156598 -0.031579  0.649826
E  2.154846 -0.610259 -0.755325 -0.346419

In [35]:
df

W         X         Y         Z       new
A -0.497104 -0.754070 -0.943406  0.484752 -1.697476
B -0.116773  1.901755  0.238127  1.996652  2.139882
C -0.993263  0.196800 -1.136645  0.000366 -0.939845
D  1.025984 -0.156598 -0.031579  0.649826 -0.188177
E  2.154846 -0.610259 -0.755325 -0.346419 -1.365584

In [36]:
df.drop('new',axis=1,inplace=True)

In [37]:
df

W         X         Y         Z
A -0.497104 -0.754070 -0.943406  0.484752
B -0.116773  1.901755  0.238127  1.996652
C -0.993263  0.196800 -1.136645  0.000366
D  1.025984 -0.156598 -0.031579  0.649826
E  2.154846 -0.610259 -0.755325 -0.346419

In [38]:
df.drop('E',axis=0)

W         X         Y         Z
A -0.497104 -0.754070 -0.943406  0.484752
B -0.116773  1.901755  0.238127  1.996652
C -0.993263  0.196800 -1.136645  0.000366
D  1.025984 -0.156598 -0.031579  0.649826

In [42]:
df.shape

(5, 4)

In [43]:
df.loc['A']

W   -0.497104
X   -0.754070
Y   -0.943406
Z    0.484752
Name: A, dtype: float64

In [44]:
df.iloc[0]

W   -0.497104
X   -0.754070
Y   -0.943406
Z    0.484752
Name: A, dtype: float64

In [46]:
df.loc['A','X']

-0.7540697010400628

In [49]:
df.loc[['A','B'],['X','Y','Z']]

X         Y         Z
A -0.754070 -0.943406  0.484752
B  1.901755  0.238127  1.996652

# Pandas -DataFrames part2

In [51]:
#conditional selection
df>0
booldf=df>0

In [52]:
booldf

W      X      Y      Z
A  False  False  False   True
B  False   True   True   True
C  False   True  False   True
D   True  False  False   True
E   True  False  False  False

In [53]:
df[booldf]

W         X         Y         Z
A       NaN       NaN       NaN  0.484752
B       NaN  1.901755  0.238127  1.996652
C       NaN  0.196800       NaN  0.000366
D  1.025984       NaN       NaN  0.649826
E  2.154846       NaN       NaN       NaN

In [54]:
df[df>0]

W         X         Y         Z
A       NaN       NaN       NaN  0.484752
B       NaN  1.901755  0.238127  1.996652
C       NaN  0.196800       NaN  0.000366
D  1.025984       NaN       NaN  0.649826
E  2.154846       NaN       NaN       NaN

In [55]:
df[df['W']>0]

W         X         Y         Z
D  1.025984 -0.156598 -0.031579  0.649826
E  2.154846 -0.610259 -0.755325 -0.346419

In [57]:
df[df['Z']<0]

W         X         Y         Z
E  2.154846 -0.610259 -0.755325 -0.346419

In [58]:
df[df['Z']<0]['W']

E    2.154846
Name: W, dtype: float64

In [60]:
#single line abstraction
df[df['Z']<0][['W','Z']]

W         Z
E  2.154846 -0.346419

In [63]:
df[(df['X']>0) & (df['Y']>0)]

W         X         Y         Z
B -0.116773  1.901755  0.238127  1.996652

In [65]:
df[(df['X']>0) | (df['Y']>0)]

W         X         Y         Z
B -0.116773  1.901755  0.238127  1.996652
C -0.993263  0.196800 -1.136645  0.000366

In [66]:
df

W         X         Y         Z
A -0.497104 -0.754070 -0.943406  0.484752
B -0.116773  1.901755  0.238127  1.996652
C -0.993263  0.196800 -1.136645  0.000366
D  1.025984 -0.156598 -0.031579  0.649826
E  2.154846 -0.610259 -0.755325 -0.346419

In [67]:
df['states']=['AX','BZ','CA','DF','PN']

In [68]:
df

W         X         Y         Z states
A -0.497104 -0.754070 -0.943406  0.484752     AX
B -0.116773  1.901755  0.238127  1.996652     BZ
C -0.993263  0.196800 -1.136645  0.000366     CA
D  1.025984 -0.156598 -0.031579  0.649826     DF
E  2.154846 -0.610259 -0.755325 -0.346419     PN

In [69]:
df.reset_index()

index         W         X         Y         Z states
0     A -0.497104 -0.754070 -0.943406  0.484752     AX
1     B -0.116773  1.901755  0.238127  1.996652     BZ
2     C -0.993263  0.196800 -1.136645  0.000366     CA
3     D  1.025984 -0.156598 -0.031579  0.649826     DF
4     E  2.154846 -0.610259 -0.755325 -0.346419     PN

In [73]:
df.set_index('states')

W         X         Y         Z
states                                        
AX     -0.497104 -0.754070 -0.943406  0.484752
BZ     -0.116773  1.901755  0.238127  1.996652
CA     -0.993263  0.196800 -1.136645  0.000366
DF      1.025984 -0.156598 -0.031579  0.649826
PN      2.154846 -0.610259 -0.755325 -0.346419

In [71]:
df.reset_index()

index         W         X         Y         Z states
0     A -0.497104 -0.754070 -0.943406  0.484752     AX
1     B -0.116773  1.901755  0.238127  1.996652     BZ
2     C -0.993263  0.196800 -1.136645  0.000366     CA
3     D  1.025984 -0.156598 -0.031579  0.649826     DF
4     E  2.154846 -0.610259 -0.755325 -0.346419     PN

In [74]:
df

W         X         Y         Z states
A -0.497104 -0.754070 -0.943406  0.484752     AX
B -0.116773  1.901755  0.238127  1.996652     BZ
C -0.993263  0.196800 -1.136645  0.000366     CA
D  1.025984 -0.156598 -0.031579  0.649826     DF
E  2.154846 -0.610259 -0.755325 -0.346419     PN

#  Pandas -DataFrames part3

In [76]:
inside=[1,2,3,1,2,3]
outside=['G1','G1','G1','G2','G2','G2']

heir_index=(list(zip(outside,inside)))

In [81]:
heir_index=pd.MultiIndex.from_tuples(heir_index)

In [82]:
heir_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           codes=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [83]:
df=pd.DataFrame(randn(6,2),heir_index,['A','B'])

In [84]:
df

A         B
G1 1  0.992573  1.192241
   2 -1.046780  1.292765
   3 -1.467514 -0.494095
G2 1 -0.162535  0.485809
   2  0.392489  0.221491
   3 -0.855196  1.541990

In [85]:
df.loc['G1']

A         B
1  0.992573  1.192241
2 -1.046780  1.292765
3 -1.467514 -0.494095

In [86]:
df.loc['G1'].loc[1]

A    0.992573
B    1.192241
Name: 1, dtype: float64

In [87]:
df

A         B
G1 1  0.992573  1.192241
   2 -1.046780  1.292765
   3 -1.467514 -0.494095
G2 1 -0.162535  0.485809
   2  0.392489  0.221491
   3 -0.855196  1.541990

In [88]:
df.loc['G1']

A         B
1  0.992573  1.192241
2 -1.046780  1.292765
3 -1.467514 -0.494095

In [91]:
df.xs('G1')

A         B
1  0.992573  1.192241
2 -1.046780  1.292765
3 -1.467514 -0.494095

In [97]:
#df.xs(1,level='Num')

# MissingData

In [103]:
d={'A':[1,2,np.NaN],'B':[1,np.NaN,3],'C':[1,2,3]}

In [104]:
df=pd.DataFrame(d)

In [105]:
df

A    B  C
0  1.0  1.0  1
1  2.0  NaN  2
2  NaN  3.0  3

In [106]:
df.dropna()

A    B  C
0  1.0  1.0  1

In [107]:
df.dropna(thresh=2)

A    B  C
0  1.0  1.0  1
1  2.0  NaN  2
2  NaN  3.0  3

In [111]:
df.fillna(df['A'].mean())

A    B  C
0  1.0  1.0  1
1  2.0  1.5  2
2  1.5  3.0  3

# GroupBy

### group together rows based on a column and an aggregate function on them

In [3]:
import numpy as np
import pandas as pd
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [5]:
df=pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [9]:
byCom = df.groupby('Company')


In [12]:
byCom.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [15]:
byCom.sum().loc['FB']

Sales    593
Name: FB, dtype: int64

In [16]:
df.groupby('Company').count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [17]:
df.groupby('Company').max()

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [24]:
df.groupby('Company').describe().loc['FB']

Sales  count      2.000000
       mean     296.500000
       std       75.660426
       min      243.000000
       25%      269.750000
       50%      296.500000
       75%      323.250000
       max      350.000000
Name: FB, dtype: float64

## Merging Joining and Concatenating

In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [3]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [12]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [13]:
print(df1)
print(df2)
print(df3)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7
      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11


In [14]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [15]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [16]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})  

In [17]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [18]:
right

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

### Merging¶
### The merge function allows you to merge DataFrames together using a similar logic as merging SQL Tables together. For example:

In [19]:
pd.merge(left,right,how='inner',on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

## Operations

In [1]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [2]:
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [3]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [5]:
df['col2'].unique()

array([444, 555, 666])

In [6]:
len(df['col2'].unique())

3

In [8]:
#no of unique values
df['col2'].nunique()

3

In [9]:
#unique value counts
df['col2'].value_counts()


444    2
555    1
666    1
Name: col2, dtype: int64

In [13]:
#conditional selectional
df[(df['col1']>2) & (df['col2']>500)]

col1  col2 col3
2     3   666  ghi

In [16]:
df['col1'].sum()

10

In [18]:
def times(x):
    return x*x

In [19]:
#not only we can use built in methods of dataframe like sum
#custom methods can also be used by using apply() method
df['col1'].apply(times)

0     1
1     4
2     9
3    16
Name: col1, dtype: int64

In [20]:
#using lambda fn
df['col1'].apply(lambda x:x*2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [22]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [23]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [24]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [25]:
df.sort_values('col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [26]:
df.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [29]:
import numpy as np
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [30]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [31]:
df.pivot_table(values='D',index=['A','B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

## Data Input and Output

In [1]:
# CSV EXCEL SQL HTML
import pandas as pd


In [36]:
pd.read_csv('example.csv')

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [37]:
df = pd.read_csv('example.csv')

In [38]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [41]:
df.to_csv('myoutput.csv',index=False)

In [42]:
conda install xlrd

Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [5]:
df = pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

In [6]:
df

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [7]:
df.to_excel('excel2.xlsx',sheet_name='sheet2')

In [9]:
conda install lxml


Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [10]:
conda install html5lib


Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [12]:
conda install BeautifulSoup4

Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


# HTML Input
### Pandas read_html function will read tables off of a webpage and return a list of DataFrame objects:

In [28]:
import pandas as pd
data = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [29]:
data

[                                             Bank Name                City  \
 0                                 The Enloe State Bank              Cooper   
 1                  Washington Federal Bank for Savings             Chicago   
 2      The Farmers and Merchants State Bank of Argonia             Argonia   
 3                                  Fayette County Bank          Saint Elmo   
 4    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
 5                                       First NBC Bank         New Orleans   
 6                                        Proficio Bank  Cottonwood Heights   
 7                        Seaway Bank and Trust Company             Chicago   
 8                               Harvest Community Bank          Pennsville   
 9                                          Allied Bank            Mulberry   
 10                        The Woodbury Banking Company            Woodbury   
 11                              First CornerStone B

In [5]:
type(data)

list

In [26]:
data[0].head()

Bank Name        City  ST   CERT  \
0                               The Enloe State Bank      Cooper  TX  10716   
1                Washington Federal Bank for Savings     Chicago  IL  30570   
2    The Farmers and Merchants State Bank of Argonia     Argonia  KS  17719   
3                                Fayette County Bank  Saint Elmo  IL   1802   
4  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...   Milwaukee  WI  30003   

                 Acquiring Institution       Closing Date      Updated Date  
0                   Legend Bank, N. A.       May 31, 2019     June 18, 2019  
1                   Royal Savings Bank  December 15, 2017     July 24, 2019  
2                          Conway Bank   October 13, 2017     July 24, 2019  
3            United Fidelity Bank, fsb       May 26, 2017  January 29, 2019  
4  First-Citizens Bank & Trust Company        May 5, 2017    March 22, 2018

In [30]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///:memory:')

In [31]:
df.to_sql('data', engine)

AttributeError: 'list' object has no attribute 'to_sql'